In [1]:
import pandas as pd

In [2]:
df = (
    pd.read_json("../artifacts/data/raw/dataset_test.jsonl", lines=True)
    .set_index(["question_id", "sample_id"])
    .sort_index()
)
df.head()

,,question,gold_answer_text,gold_answer_number,teacher_answer_text,teacher_answer_number,is_correct,finish_reason,usage,latency_ms,model,request_id
question_id,sample_id,,,,,,,,,,,
0,0,Janet’s ducks lay 16 eggs per day. She eats th...,Janet sells 16 - 3 - 4 = <<16-3-4=9>>9 duck eg...,18,Reasoning:\n- Total eggs per day: 16\n- Breakf...,18.0,True,stop,"{'prompt_tokens': 518, 'completion_tokens': 25...",6154,deepseek/deepseek-r1-distill-qwen-32b,gen-1759004857-wPzUELElNUyxLwMNyJ9v
1,0,A robe takes 2 bolts of blue fiber and half th...,It takes 2/2=<<2/2=1>>1 bolt of white fiber\nS...,3,Reasoning:\n- Blue bolts: 2\n- Half for white:...,3.0,True,stop,"{'prompt_tokens': 480, 'completion_tokens': 12...",3334,deepseek/deepseek-r1-distill-qwen-32b,gen-1759004857-ACCZea3EAhsePWQ0Wttn
2,0,Josh decides to try flipping a house. He buys...,The cost of the house and repairs came out to ...,70000,"Reasoning:\n- Total cost: $80,000 + $50,000 = ...",70000.0,True,stop,"{'prompt_tokens': 511, 'completion_tokens': 70...",15546,deepseek/deepseek-r1-distill-qwen-32b,gen-1759004857-oncZgY6EjN6zz67Ym9TN
3,0,James decides to run 3 sprints 3 times a week....,He sprints 3*3=<<3*3=9>>9 times\nSo he runs 9*...,540,Reasoning:\n- Sprints per day: 3\n- Days per w...,540.0,True,stop,"{'prompt_tokens': 489, 'completion_tokens': 16...",4430,deepseek/deepseek-r1-distill-qwen-32b,gen-1759004857-RFhoIwzDoMteHdZHRJql
4,0,"Every day, Wendi feeds each of her chickens th...","If each chicken eats 3 cups of feed per day, t...",20,Reasoning:\n- Total daily feed needed: 20 chic...,20.0,True,stop,"{'prompt_tokens': 565, 'completion_tokens': 33...",7927,deepseek/deepseek-r1-distill-qwen-32b,gen-1759004857-eVZRFRbVkRt9awQoh4Vr

In [9]:
df["is_correct"].mean()

np.float64(0.9361046959199384)